sudo: false
language: node_js
arch:
  - amd64
  - ppc64le
before_install:
  - npm install -g npm@2
  - test $NPM_LEGACY && npm install -g npm@latest-3 || npm install npm -g
notifications:
  email: false
matrix:
  fast_finish: true
  include:
  - node_js: '8'
    env:
      - TASK=test
      - NPM_LEGACY=true
  - node_js: '10'
    env:
      - TASK=test
      - NPM_LEGACY=true
  - node_js: '12'
    env:
      - TASK=test
      - NPM_LEGACY=true
  - node_js: 11
    env:
      - TASK=test
      - NPM_LEGACY=true
  - node_js: 12
    env:
      - TASK=test
      - NPM_LEGACY=true
  - node_js: 13
    env:
      - TASK=test
      - NPM_LEGACY=true
  - node_js: 14
    env:
      - TASK=test
      - NPM_LEGACY=true
  - node_js: 5
    env:
      - TASK=test
      - NPM_LEGACY=true
  - node_js: 6
    env: TASK=test
  - node_js: 7
    env: TASK=test
  - node_js: 8
    env: TASK=test
  - node_js: 9
    env: TASK=test
